[project]
name = "amazonresponseclassifier"
version = "0.1.0"
description = ""
authors = [
    {name = "Дмитрий Цитман",email = "dimazzik@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy (>=2.3.2,<3.0.0)",
    "matplotlib (>=3.10.5,<4.0.0)",
    "scipy (>=1.16.1,<2.0.0)",
    "pytest (>=8.4.1,<9.0.0)",
    "scikit-learn (>=1.7.1,<2.0.0)"
]


[tool.poetry]
packages = [{include = "dmia", from="."}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
